# Copyright (c) 2020 Felix Soubelet <felix.soubelet@cern.ch>


# Project information
site_name: OMC Documentation
site_description: >-
  Documentation pages for the OMC Team at CERN. Content includes documentation
  on our activities, workflows and software as well as resources for members.
site_author: Felix Soubelet
#site_url: ''


# Repository
#repo_name: 'PyLHC'
#repo_url: 'https://github.com/pylhc'
repo_name: 'FSoubelet'
repo_url: 'https://github.com/fsoubelet/'
edit_uri: 'OMC_Draft_Site/edit/master/docs/'


# Copyright
copyright: 'Copyright &copy; 2020 Felix Soubelet'


# Configuration
theme:
  name: 'material'
  custom_dir: docs/theme_override_home/
  logo: assets/logos/OMC_logo_inverse.svg  # top left header logo
  favicon: assets/logos/OMC_logo.svg  # browser tab logo
  # Default Values
  language: en
  features:
    - navigation.tabs
    - navigation.instant
  palette:
    scheme: preference
    primary: indigo
    accent: deep purple #amber #red
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search
  - minify:
      minify_html: true


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.keys:
      key_map: {"okbtn": "OK", "cancelbtn": "Cancel", "mousewheel": "Mouse Wheel"}
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pylhc
      name: OMC's Organisation on Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:OMC-team@cern.ch
      name: Email the OMC team

# Extras to load
extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Site Layout
nav:
  - Home: index.md
  - The OMC Team:
    - About: omc_team/about.md
    - Future MD Ideas: omc_team/ideas.md
    - Physics of OMC: omc_team/physics.md
    - OMC Methods: omc_team/methods.md
    - Publications: omc_team/publications.md
  - Python Packages:
    - The OMC Packages: packages/about.md
    - The omc3 Package:
      - About omc3: packages/omc3/about.md
      - Getting Started: packages/omc3/getting_started.md
      - Workflow: packages/omc3/workflow.md
      - Know-How: packages/omc3/know_how.md
    - Other Packages:
      - Beta-Beat.src: packages/betabeatsrc.md
      - pylhc: packages/pylhc.md
      - tfs-pandas: packages/tfs-pandas.md
      - sdds: packages/sdds.md
      - generic_parser: packages/generic_parser.md
      - MESS: packages/mess.md
    - Python Development: packages/development.md
  - The OMC GUIs:
    - The OMC GUIs: guis/about.md
    - Beta-Beat GUI:
      - About: guis/betabeat/gui.md
      - Beam Selection: guis/betabeat/beam_selection.md
      - BPM Panel: guis/betabeat/bpm_panel.md
      - Analysis Panel: guis/betabeat/analysis_panel.md
      - Optics Panel: guis/betabeat/optics_panel.md
      - Correction Panel: guis/betabeat/correction_panel.md
      - The omc3 branch: guis/betabeat/omc3.md
    - Kmod GUI:
      - About: guis/kmod/gui.md
      - Loading a Model: guis/kmod/load_model.md
      - Full IP Trim: guis/kmod/full_ip_trim.md
      - Magnet Modulation: guis/kmod/individual_modulation.md
      - Analyzing Trim Data: guis/kmod/trim_analysis.md
      - Using Auto Trim: guis/kmod/autotrim.md
    - Multiturn GUI:
        - About: guis/multiturn/gui.md
    - Developing the GUIs:
      - IDE Setup: guis/developing/ide_install.md
      - Releases: guis/developing/releases.md
      - KMod GUI hints: guis/developing/kmod_special.md
  - Procedures:
      - Info: procedures/info.md
      - K Modulation: procedures/kmod.md
      - Amplitude Detuning: procedures/ampdet.md
      - Crossing Angle Scan: procedures/xing_scan.md
  - Resources:
      - Useful Links: resources/links.md
      - How To's:
        - Setup: resources/howto/setup.md
        - Teleworking: resources/howto/teleworking.md
      - Publications: resources/publications.md
      - FAQ: resources/faqs.md
