# Copyright (c) 2020 Felix Soubelet <felix.soubelet@cern.ch>


# Project information
site_name: OMC Documentation
site_description: Documentation Pages for the OMC3 Python Package
site_author: Felix Soubelet
#site_url: ''


# Repository
#repo_name: 'PyLHC'
#repo_url: 'https://github.com/pylhc'
repo_name: 'FSoubelet'
repo_url: 'https://github.com/fsoubelet/'
edit_uri: 'doc_omc/edit/master/docs/'


# Copyright
copyright: 'Copyright &copy; 2020 Felix Soubelet'


# Configuration
theme:
  name: 'material'
  logo: assets/logos/OMC_logo_inverse.svg
  favicon: assets/logos/OMC_logo.svg  
  # Default Values
  language: en
  features:
    - navigation.tabs
    - navigation.instant
  palette:
    scheme: preference
    primary: indigo
    accent: amber #red
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - css/extra.css

# Plugins
plugins:
  - search
  - minify:
      minify_html: true


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.keys:
      key_map: {"okbtn": "OK", "cancelbtn": "Cancel", "mousewheel": "Mouse Wheel"}
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pylhc
    
# Site Layout
nav:
  - The OMC Team: index.md
  - Ideas: general/ideas.md
  - Physics of OMC: general/physics.md
  - OMC Methods: general/methods.md
  - OMC Resources: general/resources.md
  - Publications: general/publications.md
  - FAQ: general/faqs.md
  - Python Packages:
    - The OMC Packages: packages/about.md
    - The omc3 Package:
      - About omc3: packages/omc3/about.md
      - Getting Started: packages/omc3/getting_started.md
      - Workflow: packages/omc3/workflow.md
      - Know-How: packages/omc3/know_how.md
    - Other Packages:
      - tfs-pandas: packages/tfs-pandas.md
      - sdds: packages/sdds.md
      - PyLHC: packages/pylhc.md
      - generic_parser: packages/generic_parser.md
      - Beta-Beat.src: packages/betabeatsrc.md
      - MESS: packages/mess.md
    - Python Development: packages/development.md
  - Beta-Beat GUI:
    - The Beta-Beat GUI: guis/betabeat/gui.md
    - Running the GUI:
      - Basics: guis/betabeat/running.md
      - BPM Panel: guis/betabeat/bpm_panel.md
      - Analysis Panel: guis/betabeat/analysis_panel.md
      - Optics Panel: guis/betabeat/optics_panel.md
      - Correction Panel: guis/betabeat/correction_panel.md
    - Running the GUI (omc3):
      - Important: guis/betabeat/omc3.md
    - Developing the GUI:
      - IDE Setup: guis/betabeat/ide_install.md
      - Releases: guis/betabeat/releases.md
  - Kmod GUI:
    - The Kmod GUI: guis/kmod/gui.md
    - Running the GUI: 
      - Basic: guis/kmod/running.md
      - Full IP Trim: guis/kmod/full_ip_trim.md
      - Magnet Modulation: guis/kmod/individual_modulation.md
      - Analyzing Trim Data: guis/kmod/trim_analysis.md
      - Using Auto Trim: guis/kmod/autotrim.md
    - Developing the GUI:
      - IDE Setup: guis/kmod/ide_install.md
      - Releases: guis/kmod/releases.md
  - Multiturn GUI:
      - The Multiturn GUI: guis/multiturn/gui.md
      - Running the GUI: guis/multiturn/running.md
  - Tips & Tricks:
      - Links: general/links.md
      - Tricks: general/tricks.md
      - Publications: general/publications.md
